export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Neville Alumni & Friends Association",
  headline: "The backbone of the Neville Nation!",
  description:
    "\n- Support scholarships for our Tigers.\n- Beautification projects for our school.\n- Excellence in higher education at NHS.",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/reunion.jpeg"),
  alt: "reunion",
  dark: false,
  primary: false,
  darkText: true,
  to: "/register",
};

export const homeObjTwo = {
  id: "membership",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Membership",
  headline: "Show support for Neville and Alumni",
  description:
    "We have you covered no matter where you are located. You can still support and be a part of Neville community.",
  buttonLabel: "Learn more",
  imgStart: true,
  img: require("../../images/Scholarship_Nafa.jpg"),
  alt: "members",
  dark: true,
  primary: true,
  darkText: false,
  to: "/payments",
};

export const homeObjThree = {
  id: "events",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "NAFA Events",
  headline: "Follow our past and future events",
  description:
    "Get everthing set up and ready in under 5 minutes. All you need to do is add your information and you are ready to go.",
  buttonLabel: "Go to all events",
  imgStart: false,
  img: require("../../images/png-2.png"),
  alt: "papers",
  dark: true,
  primary: true,
  darkText: false,
  to: "/event",
};

export const homeObjFour = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Lets join and support our Tigers",
  headline: "Creating an account is extremely easy",
  description:
    "Get everthing set up and ready in under 5 minutes. All you need to do is add your information and you are ready to go.",
  buttonLabel: "Start now",
  imgStart: false,
  img: require("../../images/png-2.png"),
  alt: "papers",
  dark: false,
  primary: false,
  darkText: true,
  to: "/register",
};

export const userAccountObj = {
  id: "account",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Sajin Shrestha",
  headline: "Graduate of 2022",
  description: "sajinshrestha74@gmail.com\n(318) 791 6729",
  buttonLabel: "More...",
  imgStart: false,
  img: require("../../images/profile.png"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/account",
};

export const userPaymentObj = {
  id: "payments",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Lets join and support our Tigers",
  headline: "Your small support makes huge difference.",
  description: "We have various option for you all...",
  buttonLabel: "Membership payment",
  imgStart: false,
  img: require("../../images/png-2.png"),
  alt: "papers",
  dark: false,
  primary: false,
  darkText: true,
  to: "/payment",
};
