export const userObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  flname: "Sajin Shrestha",
  who: "Class of 2022",
  email: "sajinshrestha74@gmail.com",
  phone: "(318) 791 6729",
  address1: "802 Warhawks way",
  address2: "Apt. 1",
  city: "Monroe",
  state: "LA",
  zip: "71203",
  buttonLabel: "Edit",
  imgStart: false,
  img: require("../../images/profile.png"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/account",
};
