export const userObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Sajin Shrestha",
  headline: "Graduate of 2022",
  description: "sajinshrestha74@gmail.com\n(318) 791 6729",
  buttonLabel: "More...",
  imgStart: false,
  img: require("../../images/profile.png"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/account",
};

export const userObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Lets join and support our Tigers",
  headline: "Your small support makes huge difference.",
  description: "We have various option for you all...",
  buttonLabel: "Membership payment",
  imgStart: false,
  img: require("../../images/png-2.png"),
  alt: "papers",
  dark: false,
  primary: false,
  darkText: true,
  to: "/account"
};
